name: ToDo App Workflow

# このワークフローは、リポジトリにプッシュされたときにトリガーされます
on: [push]

jobs:
  build:
    # Ubuntu 最新バージョンのランナーを使用
    runs-on: ubuntu-latest

    steps:
    # リポジトリのコードをチェックアウト
    - name: Checkout code
      uses: actions/checkout@v2

    # Docker Compose をインストール
    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    # Azure Container Registry (ACR) にログイン
    - name: Log in to ACR
      uses: azure/docker-login@v1
      with:
        login-server: acrudemylearn-b6gjgtfqcpedffhj.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }} # ACRのユーザー名
        password: ${{ secrets.REGISTRY_PASSWORD }} # ACRのパスワード
    
    # Docker Compose を使用してイメージをビルドし、ACR にプッシュ
    - name: Build and Push Docker Image
      # 環境変数を設定（Cosmos DBのエンドポイントとキーを使用）
      env:
        COSMOS_DB_ENDPOINT: ${{ secrets.COSMOS_DB_ENDPOINT }}
        COSMOS_DB_KEY: ${{ secrets.COSMOS_DB_KEY }}
      # Docker Compose を使用してプロダクション用のイメージをビルド
      # ビルドしたイメージをACRにタグ付けしてプッシュ
      run: |
        docker-compose -f docker-compose.prod.yml build \
          --build-arg COSMOS_DB_ENDPOINT="${COSMOS_DB_ENDPOINT}" \
          --build-arg COSMOS_DB_KEY="${COSMOS_DB_KEY}"
        docker tag todo-app:latest acrudemylearn-b6gjgtfqcpedffhj.azurecr.io/todo-app:${{ github.sha }}
        docker push acrudemylearn-b6gjgtfqcpedffhj.azurecr.io/todo-app:${{ github.sha }}

  deploy:
    # デプロイフェーズはビルドフェーズが完了してから実行
    needs: build
    runs-on: ubuntu-latest

    steps:
    
    # Azureにログイン
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    # Azure Container Apps にデプロイ
    - name: deploy Container App
      uses: azure/container-apps-deploy-action@v1
      with:
        # ACRの名前を指定
        acrName: acrudemylearn-b6gjgtfqcpedffhj
        # デプロイするコンテナアプリの名前
        containerAppName: todoapp
        # リソースグループの名前
        resourceGroup: udemy-container-cicd
        # デプロイするイメージを指定
        imageToDeploy: acrudemylearn-b6gjgtfqcpedffhj.azurecr.io/todo-app:${{ github.sha }}
        # 環境変数をコンテナアプリに渡す
        environmentVariables: "COSMOS_DB_ENDPOINT='${{ secrets.COSMOS_DB_ENDPOINT }}' COSMOS_DB_KEY='${{ secrets.COSMOS_DB_KEY }}' SENDER_EMAIL='${{ secrets.SENDER_EMAIL }}' EMAIL_PASSWORD='${{ secrets.EMAIL_PASSWORD }}' RECIPIENT_EMAIL='${{ secrets.RECIPIENT_EMAIL }}'"